"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Download, RotateCcw } from "lucide-react";
import { CartesianGrid, Legend, Line, LineChart, Pie, PieChart, Tooltip, XAxis, YAxis } from "recharts";
import { ResponsiveContainer } from "@/components/analytics/AnalyticsChartContainer";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingState } from "@/components/ui/LoadingState";
import { polishMonthNames } from "@/lib/completed-games";
import { metacriticValueLabel } from "@/lib/external-ratings";
import { asDate, formatHours } from "@/lib/utils";
import { api } from "@/services/api";
import type { CompletedGameHighlight, CompletedGamesPeriodDifference, CompletedGamesYearReport } from "@/types";

export function AnnualReport({ year }: { year: number }) {
  const [report, setReport] = useState<CompletedGamesYearReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [retry, setRetry] = useState(0);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(null); api.getCompletedYearReport(year, controller.signal).then(setReport).catch((reason) => { if (!(reason instanceof DOMException && reason.name === "AbortError")) setError(reason instanceof Error ? reason.message : "Nie udało się wygenerować raportu."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [retry, year]);
  if (loading) return <LoadingState label="Generowanie raportu rocznego" />;
  if (error) return <div className="space-y-3"><ErrorState message={error} /><Button variant="secondary" onClick={() => setRetry((value) => value + 1)}><RotateCcw className="h-4 w-4" aria-hidden="true" />Spróbuj ponownie</Button></div>;
  if (!report) return null;
  return <ReportContent report={report} />;
}

function ReportContent({ report }: { report: CompletedGamesYearReport }) {
  const s = report.summary;
  const poePlaytime = s.poe_playtime_hours ?? 0;
  const combinedPlaytime = s.combined_playtime_hours ?? s.total_playtime_hours + poePlaytime;
  const monthlyChart = report.monthly.map((item) => ({ month: polishMonthNames[item.month - 1].slice(0, 3), games: item.completed_games_count }));
  const platformPie = compactPlatforms(report.platforms);
  return <section className="annual-report-print space-y-6" aria-labelledby="annual-report-heading">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Games Tracker</p><h2 id="annual-report-heading" className="mt-1 text-2xl font-bold">Raport roczny — {report.year}</h2><p className="mt-1 text-sm text-muted-foreground">Wygenerowano: {new Intl.DateTimeFormat("pl-PL", { dateStyle: "long", timeStyle: "short" }).format(new Date(report.generated_at))}</p></div><Button type="button" className="print-hide" onClick={() => window.print()}><Download className="h-4 w-4" aria-hidden="true" />Zapisz jako PDF</Button></header>
    {!s.completed_games_count && !(s.poe_leagues_count ?? 0) ? <Card className="border-dashed"><CardContent className="p-8 text-center"><p className="font-semibold">Brak ukończonych gier i lig PoE w {report.year} roku.</p><p className="mt-1 text-sm text-muted-foreground">Raport zawiera puste miesiące, ale nie generuje mylących statystyk.</p></CardContent></Card> : null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ReportStat label="Ukończone gry" value={String(s.completed_games_count)} /><ReportStat label="Ukończone ligi PoE" value={String(s.poe_leagues_count ?? 0)} /><ReportStat label="Łączny czas" value={combinedPlaytime > 0 ? formatHours(combinedPlaytime) : "Brak danych"} /><ReportStat label="Czas w PoE" value={poePlaytime > 0 ? formatHours(poePlaytime) : "Brak danych"} /><ReportStat label="Średni czas gry singleplayer" value={s.average_playtime_hours == null ? "Brak danych" : formatHours(s.average_playtime_hours)} /><ReportStat label="Mediana czasu" value={s.median_playtime_hours == null ? "Brak danych" : formatHours(s.median_playtime_hours)} /><ReportStat label="Średnia ocena" value={s.average_rating == null ? "Brak ocen" : `${formatNumber(s.average_rating)}/10`} /><ReportStat label="Mediana ocen" value={s.median_rating == null ? "Brak ocen" : `${formatNumber(s.median_rating)}/10`} /><ReportStat label="Ocenione / nieocenione" value={`${s.rated_games_count} / ${s.unrated_games_count}`} /><ReportStat label="Platformy / gatunki" value={`${s.unique_platforms_count} / ${s.unique_genres_count}`} /></div>
    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Najważniejsze gry</CardTitle></CardHeader><CardContent className="space-y-2"><Highlight label="Najlepiej oceniona" game={s.best_rated_game} value={s.best_rated_game?.rating == null ? "Brak ocen" : `${formatNumber(s.best_rated_game.rating)}/10`} /><Highlight label="Najdłuższa" game={s.longest_game} value={s.longest_game ? formatHours(s.longest_game.playtime_hours) : "Brak czasu"} /><Highlight label="Najkrótsza" game={s.shortest_game} value={s.shortest_game ? formatHours(s.shortest_game.playtime_hours) : "Brak czasu"} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Najważniejsze wydarzenia</CardTitle></CardHeader><CardContent><dl className="grid gap-2 text-sm"><Event label="Pierwsze ukończenie" value={gameEvent(report.first_completion)} /><Event label="Ostatnie ukończenie" value={gameEvent(report.last_completion)} /><Event label="Najdłuższa seria aktywnych miesięcy" value={`${report.longest_active_streak_months} mies.`} /><Event label="Najaktywniejszy miesiąc" value={monthEvent(report.most_active_month, "games")} /><Event label="Najwięcej czasu" value={monthEvent(report.most_playtime_month, "time")} /><Event label="Najbardziej zróżnicowany miesiąc" value={report.most_diverse_month ? `${polishMonthNames[report.most_diverse_month.month - 1]} · ${report.most_diverse_month.unique_genres_count} gatunków` : "Brak danych"} /></dl></CardContent></Card>
    </div>
    {report.insights.length ? <Card><CardHeader><CardTitle>Automatyczne wnioski</CardTitle><CardDescription>Wnioski są tworzone deterministycznie z danych raportu, bez użycia LLM.</CardDescription></CardHeader><CardContent><ul className="grid gap-2 sm:grid-cols-2">{report.insights.map((item) => <li key={item} className="rounded-md bg-muted/55 p-3 text-sm">{item}</li>)}</ul></CardContent></Card> : null}
    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Ukończenia miesiąc po miesiącu</CardTitle></CardHeader><CardContent><div className="h-72" role="img" aria-label={`Miesięczna liczba ukończeń w ${report.year} roku`}><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyChart}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="month" stroke="#94a3b8" /><YAxis allowDecimals={false} stroke="#94a3b8" /><Tooltip contentStyle={tooltipStyle} /><Line dataKey="games" name="Ukończenia" stroke="#34d399" strokeWidth={3} isAnimationActive={false} /></LineChart></ResponsiveContainer></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Udział platform</CardTitle></CardHeader><CardContent>{platformPie.length ? <div className="h-72" role="img" aria-label="Udział platform w raporcie rocznym"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={platformPie} dataKey="value" nameKey="name" innerRadius="45%" outerRadius="75%" isAnimationActive={false} label={({ name, percent }) => `${name} ${Math.round((percent ?? 0) * 100)}%`} /><Tooltip contentStyle={tooltipStyle} /><Legend /></PieChart></ResponsiveContainer></div> : <p className="text-sm text-muted-foreground">Brak danych o platformach.</p>}</CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>Zestawienie miesięczne</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b border-border text-muted-foreground"><tr><th className="p-2">Miesiąc</th><th className="p-2">Gry</th><th className="p-2">Czas</th><th className="p-2">Średni czas</th><th className="p-2">Mediana czasu</th><th className="p-2">Średnia ocena</th><th className="p-2">Najlepsza gra</th></tr></thead><tbody>{report.monthly.map((item) => <tr key={item.month} className="border-b border-border/60"><td className="p-2 font-medium">{polishMonthNames[item.month - 1]}</td><td className="p-2">{item.completed_games_count}</td><td className="p-2">{item.games_with_playtime_count ? formatHours(item.total_playtime_hours) : "Brak danych"}</td><td className="p-2">{item.average_playtime_hours == null ? "Brak danych" : formatHours(item.average_playtime_hours)}</td><td className="p-2">{item.median_playtime_hours == null ? "Brak danych" : formatHours(item.median_playtime_hours)}</td><td className="p-2">{item.average_rating == null ? "Brak ocen" : `${formatNumber(item.average_rating)}/10`}</td><td className="p-2">{item.best_rated_game?.title ?? "Brak ocen"}</td></tr>)}</tbody></table></CardContent></Card>
    {report.previous_year ? <Card><CardHeader><CardTitle>Porównanie z {report.previous_year} rokiem</CardTitle><CardDescription>Przy zerowej wartości bazowej pokazujemy zmianę bezwzględną bez mylącego procentu.</CardDescription></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2">{report.previous_year_differences.map((item) => <YearDifference key={item.metric} item={item} />)}</CardContent></Card> : null}
  </section>;
}

function ReportStat({ label, value }: { label: string; value: string }) { return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></CardContent></Card>; }
function Highlight({ label, game, value }: { label: string; game?: CompletedGameHighlight | null; value: string }) { return <div className="rounded-md border border-border bg-background/45 p-3 text-sm"><p className="text-xs text-muted-foreground">{label}</p>{game ? <Link href={`/completed-games/entry/${game.id}`} className="mt-1 block hover:text-accent"><span className="flex justify-between gap-3 font-semibold"><span>{game.title}</span><span>{value}</span></span><span className="mt-1 block text-xs text-muted-foreground">Metacritic: {metacriticValueLabel(game.external_ratings)}</span></Link> : <p className="mt-1 font-semibold">{value}</p>}</div>; }
function Event({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-border/60 py-2 last:border-0"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-semibold">{value}</dd></div>; }
function YearDifference({ item }: { item: CompletedGamesPeriodDifference }) { const labels: Record<string,string> = {completed_games_count:"Ukończone gry",total_playtime_hours:"Łączny czas",average_rating:"Średnia ocena",average_playtime_hours:"Średni czas"}; return <div className="rounded-md bg-muted/55 p-3 text-sm"><p className="text-xs text-muted-foreground">{labels[item.metric] ?? item.metric}</p><p className="mt-1 font-semibold">Zmiana: {item.absolute_change == null ? "Brak danych" : `${item.absolute_change > 0 ? "+" : ""}${formatNumber(item.absolute_change)}`}</p><p className="text-xs text-muted-foreground">{item.percentage_change != null ? `${item.percentage_change > 0 ? "+" : ""}${formatNumber(item.percentage_change)}%` : item.previous_value === 0 ? "Brak wartości bazowej do obliczenia zmiany procentowej." : "Brak porównywalnych danych"}</p></div>; }
function gameEvent(game?: CompletedGameHighlight | null) { return game ? `${game.title} · ${asDate(game.completion_date)} · Metacritic: ${metacriticValueLabel(game.external_ratings)}` : "Brak danych"; }
function monthEvent(item: CompletedGamesYearReport["most_active_month"], metric: "games" | "time") { if (!item) return "Brak danych"; return `${polishMonthNames[item.month - 1]} · ${metric === "games" ? `${item.completed_games_count} gier` : formatHours(item.total_playtime_hours)}`; }
function compactPlatforms(items: CompletedGamesYearReport["platforms"]) { const colors = ["#34d399","#22d3ee","#a78bfa","#fbbf24","#fb7185","#94a3b8"]; const valid = items.filter((item) => !item.label.startsWith("Brak ")); const head = valid.slice(0,5).map((item,index) => ({name:item.label,value:item.completed_games_count,fill:colors[index]})); const rest=valid.slice(5).reduce((sum,item)=>sum+item.completed_games_count,0); if(rest) head.push({name:"Inne",value:rest,fill:colors[5]}); return head; }
function formatNumber(value: number) { return new Intl.NumberFormat("pl-PL", { maximumFractionDigits: 2 }).format(value); }
const tooltipStyle = { backgroundColor: "#020617", border: "1px solid #334155", borderRadius: "8px", color: "#f8fafc" };
